[package]
name = "linapi"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"
publish = false
#
license = "MIT OR Apache-2.0"
description = "High level bindings to various Linux APIs and interfaces"

[dependencies]
nix = "0.15.0"
libc = "0.2.64"
