[package]
name = "linapi"
version = "0.1.2-alpha.0"
authors = ["Diana"]
edition = "2018"
#
license = "MIT OR Apache-2.0"
description = "High level bindings to various Linux APIs and interfaces"
documentation = "https://docs.rs/linapi"
repository = "https://github.com/DianaNites/linapi"
readme = "README.md"
keywords = [
    "linux",
    "kernel",
    "modules",
]
categories = [
    "api-bindings",
    "os::unix-apis",
]

[dependencies]
nix = "0.17.0"
libc = "0.2.66"
bitflags = "1.2.1"
walkdir = "2.3.1"
goblin = "0.2.0"

[badges]
maintenance = { status = "experimental" }
